version: '3'
services:
  ssm-core:
    image: "hoanglt705/ssm-core-legacy-docker:latest"
    ports:
     - "8080:8080"
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: rootpass
