version: '2.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: root
      MYSQL_DATABASE: ssm-db
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      db: 
        condition: service_healthy
      