version: '3.7'
services:
  db:
    build:
      context: .
      dockerfile: docker/SSMDbDockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: root
      MYSQL_DATABASE: ssm-db